### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by stalkerg** [Blankeos/dot.js#5]
I just try this simple example in browser:
```js
tsdot.compile('aaa {{name}}')({name: 'test'}); 
```

And I return error `Uncaught ReferenceError: nameout is not defined`

If I do:
```js
tsdot.compile('aaa {{ name }}')({name: 'test'}); 
```

I can see more error: `Could not create a template function: var out='aaa '; name return out;`

**Comment by stalkerg** [comment]
`tsdot.template('aaa {{ name }}', null, { name: 'test'});` show same error

**Comment by Blankeos** [comment]
Thanks. Yeah, this is my bad. I will update the docs, since it doesn't reflect the actual language used by doT.js (What this fork is based on). There are lacking docs on that. In any case, the fix for this is making sure you write `{{=it.name}}` on your template.

https://stackblitz.com/edit/vitejs-vite-ktsj9hzp?file=index.html

**Comment by Blankeos** [comment]
I assume this is just a docs issue so I'll be closing this one now. Thanks! Feel free to reopen if you think otherwise.
